# check syntacs error
[[plugins]]
repo = 'vim-syntastic/syntastic'

# repeat non-native commands
[[plugins]]
repo = 'tpope/vim-repeat'

# automatically surround with parentheses
[[plugins]]
repo = 'tpope/vim-surround'

# type 'gcc' to comment out
[[plugins]]
repo = 'tpope/vim-commentary'

# type ':NERDTree' to see the file system
[[plugins]]
repo = 'preservim/nerdtree'

#[[plugins]]
#repo = 'ryanoasis/vim-devicons'

# type '<C-Y>,' to expand html/css tags
[[plugins]]
repo = 'mattn/emmet-vim'

# type ':e <file path>' to open a file in a new tab, type C-p or C-n to switch tabs
[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# eye-friendly theme
# [[plugins]]
# repo = 'jnurmine/Zenburn'

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'

[[plugins]]
repo = 'jpo/vim-railscasts-theme'

[[plugins]]
repo = 'cocopon/iceberg.vim'

# shows a git diff in the sign column
[[plugins]]
repo = 'airblade/vim-gitgutter'

# type "\t" to move the cursor to the specified letter's place
[[plugins]]
repo = 'easymotion/vim-easymotion'

# language server
# run :LspInstallServer to install a language server
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

# auto-complete
# you have to install deno to use ddc -> https://deno.land/
[[plugins]]
repo = 'Shougo/ddc.vim'
[[plugins]]
repo = 'shun/ddc-vim-lsp'

# develop vim plugins with deno
[[plugins]]
repo = 'vim-denops/denops.vim'
# pop-up window
[[plugins]]
repo = 'Shougo/pum.vim'
# complete words around the cursor
[[plugins]]
repo = 'Shougo/ddc-around'
# complete file names
[[plugins]]
repo = 'LumaKernel/ddc-file'
# complete words while typing
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
# sort words to complete
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
# remove overlapping words to complete
[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
# generate template code
[[plugins]]
repo = 'mattn/vim-sonictemplate'


# Install your UIs
[[plugins]]
repo = 'Shougo/ddc-ui-native'
# Install your sources
[[plugins]]
repo = 'Shougo/ddc-source-around'

# previous_plugin_i_had_added
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'lambdalisue/battery.vim'

[[plugins]]
repo = 'lambdalisue/wifi.vim'


[[plugins]]
repo = 'junegunn/fzf'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'previm/previm'

[[plugins]]
repo = 'mattn/vim-maketable'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'skanehira/translate.vim'

[[plugins]]
repo = 'skanehira/docker.vim'
